import { IProductModel } from "../models/product.model";

export const products: IProductModel[] = [
  {
    id: '1',
    title: 'Apeks XTX 200 DIN Octopus XTX 40 Regulator Set',
    description: 'The XTX200 is the flagship of the Apeks regulator range and the definitive blend of style and high performance. Every detail has been carefully designed to offer a regulator of the highest quality.',
    imageUrl: 'https://www.tradeinn.com/f/7/78556/apeks-xtx-200-din-octopus-xtx-40-regulator-set.jpg',
    cost: +(Math.random() * 2000).toFixed(2),
    currency: 'USD',
    isAvailable: true,
  },
  {
    id: '2',
    title: 'Scubapro Jet Diving Fins',
    description: 'SCUBAPRO Jet Fins have a long and celebrated history of performance. They set the standard for power and durability in 1965, and are still immensely popular today.',
    imageUrl: 'https://www.tradeinn.com/f/0/4307/scubapro-jet-diving-fins.jpg',
    cost: +(Math.random() * 2000).toFixed(2),
    currency: 'USD',
    isAvailable: true,
  },
  {
    id: '3',
    title: 'Ratio Ix3M2 Tech+ Computer',
    description: 'Ix3M2 Tech+ Computer. Air, Nitrox, Trimix, CCR, 10 mix, Multi Air Integrated, Huge color display, Vibration Alarm.All new User Interface with LSK, 4 Deco Algorithms, Deco Table during the dive, Compass and more.',
    imageUrl: 'https://www.tradeinn.com/f/13911/139116007/ratio-ix3m2-tech--computer.jpg',
    cost: +(Math.random() * 2000).toFixed(2),
    currency: 'USD',
    isAvailable: true,
  },
  {
    id: '4',
    title: 'SEAC Modular REV BCD',
    description: 'For those who have not yet dared to practice recreational diving, the new MODULAR REV vest will make it easier to do the job in the water. It is a very simple equipment to use, store and transfer.',
    imageUrl: 'https://www.tradeinn.com/f/13709/137090237/seac-modular-rev-bcd.jpg',
    cost: +(Math.random() * 2000).toFixed(2),
    currency: 'USD',
    isAvailable: false,
  },
  {
    id: '5',
    title: 'Cressi Calibro Mirror Spearfishing Mask',
    description: 'CALIBRO provides a group of technical advantages that Cressi has been incorporating in the last seasons in different models. It combines a great technicality with a captivating design and medium dimensions, both of the frame and of the skirt. Its exclusive structure integrates the frame in the skirt instead of overlapping them. This exclusive construction system, that allows great lightness (118 g), reduces to the absolutely minimum the thickness improving also the internal volume, the visibility and the adaptation of the mask.',
    imageUrl: 'https://www.tradeinn.com/f/13645/136450927/cressi-calibro-mirror-spearfishing-mask.jpg',
    cost: +(Math.random() * 2000).toFixed(2),
    currency: 'USD',
    isAvailable: false,
  },
  {
    id: '6',
    title: 'Scubaforce Scuba Flex Inflator Hose',
    description: 'he SCUBAFLEX inflator hoses offer a high degree of flexibility and can be perfectly configured because they have no twist at all.',
    imageUrl: 'https://www.tradeinn.com/f/13731/137314716/scubaforce-scuba-flex-inflator-hose.jpg',
    cost: +(Math.random() * 2000).toFixed(2),
    currency: 'USD',
    isAvailable: true,
  },
  {
    id: '7',
    title: 'Scubapro Everflex 7.5/5.0 mm Wetsuit',
    description: 'The ultra-warm and comfortable EVERFLEX 7/5MM uses SCUBAPRO’s exclusive Pure Design Concept for even better fit and freedom of movement than what was offered in previous versions of the suit',
    imageUrl: 'https://www.tradeinn.com/f/13921/139216897/scubapro-everflex-7.5-5.0-mm-wetsuit.jpg',
    cost: +(Math.random() * 2000).toFixed(2),
    currency: 'USD',
    isAvailable: false,
  },
  {
    id: '8',
    title: 'Scubapro Tropic 1.5 mm Gloves',
    description: 'Scubapro Tropic 1.5 mm Gloves has the 100% money-back guarantee. If for whatever reason you are not completely satisfied with your Scubapro Tropic 1.5 mm Gloves',
    imageUrl: 'https://www.tradeinn.com/f/13670/136708183/scubapro-tropic-1.5-mm-gloves.jpg',
    cost: +(Math.random() * 2000).toFixed(2),
    currency: 'USD',
    isAvailable: true,
  },
  {
    id: '9',
    title: 'Dive System Expedition Bronze Zip Dry Suit',
    description: 'Made using top-quality and resistant materials, such as the exclusive NATO Trilaminate 4-1-4 and the Kevlar. The Preformed knees and the diamond underarm gussets ensure unparalleled ergonomics and freedom of movement.\n',
    imageUrl: 'https://www.tradeinn.com/f/13918/139188153/dive-system-expedition-bronze-zip-dry-suit.jpg',
    cost: +(Math.random() * 2000).toFixed(2),
    currency: 'USD',
    isAvailable: true,
  },
]
